"""Initial migration

Revision ID: d9a13dafc4f8
Revises: 
Create Date: 2024-05-30 12:35:34.338296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a13dafc4f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_data_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_data_model_id'), 'form_data_model', ['id'], unique=False)
    op.create_table('template_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_model_id'), 'template_model', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('tab_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tab_name', sa.String(), nullable=True),
    sa.Column('tab_rename', sa.String(), nullable=True),
    sa.Column('tab_is_active', sa.String(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_model_id'), 'tab_model', ['id'], unique=False)
    op.create_table('todo_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_task_id'), 'todo_task', ['id'], unique=False)
    op.create_table('section_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('section_rename', sa.String(), nullable=True),
    sa.Column('section_is_active', sa.String(), nullable=True),
    sa.Column('tab_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tab_id'], ['tab_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_model_id'), 'section_model', ['id'], unique=False)
    op.create_table('field_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('field_rename', sa.String(), nullable=True),
    sa.Column('field_type', sa.String(), nullable=True),
    sa.Column('field_is_active', sa.String(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_model_id'), 'field_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_model_id'), table_name='field_model')
    op.drop_table('field_model')
    op.drop_index(op.f('ix_section_model_id'), table_name='section_model')
    op.drop_table('section_model')
    op.drop_index(op.f('ix_todo_task_id'), table_name='todo_task')
    op.drop_table('todo_task')
    op.drop_index(op.f('ix_tab_model_id'), table_name='tab_model')
    op.drop_table('tab_model')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_template_model_id'), table_name='template_model')
    op.drop_table('template_model')
    op.drop_index(op.f('ix_form_data_model_id'), table_name='form_data_model')
    op.drop_table('form_data_model')
    # ### end Alembic commands ###
